// Generated by CoffeeScript 1.7.1
(function() {
  var appDataDir, appDataSubDirs, config, fs, getDir, os, path, pathForFile, readFile, writeFile;

  fs = require("fs");

  os = require("os");

  path = require("path");

  config = require("../../config/config.js");

  appDataDir = void 0;

  appDataSubDirs = {};

  getDir = function(subdir) {
    if (!appDataDir) {
      if (!config.PlatformDirs[os.platform()]) {
        throw new Error("Unknown operating system: " + os.platform());
      }
      appDataDir = path.join(config.PlatformDirs[os.platform()] || "", "Airspace", "AppData");
    }
    if (subdir && !appDataSubDirs[subdir]) {
      appDataSubDirs[subdir] = path.join(appDataDir, subdir);
      if (!fs.existsSync(appDataSubDirs[subdir])) {
        fs.mkdirSync(appDataSubDirs[subdir]);
      }
    }
    if (subdir) {
      return appDataSubDirs[subdir];
    } else {
      return appDataDir;
    }
  };

  pathForFile = function(subdir, filename) {
    return path.join(getDir(subdir), filename);
  };

  readFile = function(subdir, filename) {
    return fs.readFileSync(pathForFile(subdir, filename));
  };

  writeFile = function(subdir, filename, data) {
    return fs.writeFileSync(pathForFile(subdir, filename), data);
  };

  module.exports.getDir = getDir;

  module.exports.pathForFile = pathForFile;

  module.exports.readFile = readFile;

  module.exports.writeFile = writeFile;

}).call(this);
