// Generated by CoffeeScript 1.6.3
(function() {
  var AuthorizationView, api, installManager, logOutUser, oauth, pubnub, windowChrome, withAuthorization;

  api = require('./api.js');

  installManager = require('./install-manager.js');

  oauth = require('./oauth.js');

  pubnub = require('./pubnub.js');

  windowChrome = require('./window-chrome.js');

  AuthorizationView = require('../views/authorization/authorization.js');

  withAuthorization = function(cb) {
    if (!oauth.getRefreshToken()) {
      return oauth.getAccessToken(cb);
    } else {
      return cb && cb(null);
    }
  };

  logOutUser = function() {
    var authView;
    installManager.cancelAll();
    pubnub.unsubscribeAll();
    windowChrome.rebuildMenuBar(false);
    if (uiGlobals.mainPageView) {
      uiGlobals.mainPageView.$el.remove();
      uiGlobals.mainPageView.remove();
    }
    authView = new AuthorizationView();
    return authView.logOut(function() {
      authView.remove();
      return withAuthorization(function() {
        windowChrome.paintMainPage();
        return api.connectToStoreServer();
      });
    });
  };

  module.exports.logOutUser = logOutUser;

  module.exports.withAuthorization = withAuthorization;

}).call(this);

/*
//@ sourceMappingURL=authorization-util.map
*/
