// Generated by CoffeeScript 1.6.3
(function() {
  var config, count, db, increment, reset;

  db = require("./db.js");

  config = require("../../config/config.js");

  count = function() {
    return db.fetchObj(config.DbKeys.CrashCount) || 0;
  };

  increment = function() {
    return db.saveObj(config.DbKeys.CrashCount, count() + 1);
  };

  reset = function() {
    return db.saveObj(config.DbKeys.CrashCount, 0);
  };

  module.exports.count = count;

  module.exports.increment = increment;

  module.exports.reset = reset;

}).call(this);

/*
//@ sourceMappingURL=crash-counter.map
*/
