// Generated by CoffeeScript 1.6.3
(function() {
  var convertToPng, exec, os, shell;

  os = require("os");

  exec = require("child_process").exec;

  shell = require("./shell.js");

  convertToPng = function(inputIcns, outputPng, cb) {
    var size;
    size = 96;
    if (os.platform() !== "darwin") {
      return cb(Error("icns conversion is only supported on OS X"));
    }
    return exec("sips -s format png -z " + size + " " + size + " " + shell.escape(inputIcns) + " --out " + shell.escape(outputPng), cb);
  };

  module.exports.convertToPng = convertToPng;

}).call(this);

/*
//@ sourceMappingURL=icns.map
*/
