// Generated by CoffeeScript 1.6.3
(function() {
  var NumVersionParts, areEqual, isFirstGreaterThanSecond, isFirstLessThanSecond, parseVersionString;

  NumVersionParts = 4;

  parseVersionString = function(versionString) {
    var i, versionParts;
    if (Array.isArray(versionString)) {
      return versionString;
    } else {
      versionParts = String(versionString).split(".").slice(0, NumVersionParts);
      i = 0;
      while (i < NumVersionParts) {
        versionParts[i] = parseInt(versionParts[i], 10) || 0;
        i++;
      }
      return versionParts;
    }
  };

  isFirstGreaterThanSecond = function(firstVersion, secondVersion) {
    var i;
    firstVersion = parseVersionString(firstVersion);
    secondVersion = parseVersionString(secondVersion);
    i = 0;
    while (i < NumVersionParts) {
      if (firstVersion[i] > secondVersion[i]) {
        return true;
      } else {
        if (firstVersion[i] < secondVersion[i]) {
          return false;
        }
      }
      i++;
    }
    return false;
  };

  areEqual = function(firstVersion, secondVersion) {
    var i;
    firstVersion = parseVersionString(firstVersion);
    secondVersion = parseVersionString(secondVersion);
    i = 0;
    while (i < NumVersionParts) {
      if (firstVersion[i] !== secondVersion[i]) {
        return false;
      }
      i++;
    }
    return true;
  };

  isFirstLessThanSecond = function(firstVersion, secondVersion) {
    return !isFirstGreaterThanSecond(firstVersion, secondVersion) && !areEqual(firstVersion, secondVersion);
  };

  module.exports.isFirstGreaterThanSecond = isFirstGreaterThanSecond;

  module.exports.areEqual = areEqual;

  module.exports.isFirstLessThanSecond = isFirstGreaterThanSecond;

}).call(this);
