// Generated by CoffeeScript 1.6.3
(function() {
  var escapeBash, escapeWindows, os;

  os = require("os");

  escapeBash = function(string) {
    return "'" + String(string).replace(/'/g, "'\"'\"'") + "'";
  };

  escapeWindows = function(string) {
    return "\"" + String(string).replace(/([\^<>\|])/g, "^$1").replace(/\%/g, "%") + "\"";
  };

  module.exports.escape = (os.platform() === "win32" ? escapeWindows : escapeBash);

}).call(this);

/*
//@ sourceMappingURL=shell.map
*/
