// Generated by CoffeeScript 1.6.3
(function() {
  var overriddenModules, overrideModule, path, wraprequire;

  path = require("path");

  overriddenModules = {};

  wraprequire = function(wrappedModule) {
    return function(modulepath) {
      var abspath;
      abspath = path.resolve(path.dirname(wrappedModule.id), modulepath);
      if (overriddenModules[abspath]) {
        console.log("overriding required module", abspath, "with", overriddenModules[abspath]);
      }
      return wrappedModule.require(overriddenModules[abspath] || abspath);
    };
  };

  overrideModule = function(from, to, contextmodule) {
    var absfrom, absto;
    absfrom = path.resolve(path.dirname(contextmodule.id), from);
    absto = path.resolve(path.dirname(contextmodule.id), to);
    return overriddenModules[absfrom] = absto;
  };

  module.exports = wraprequire;

  module.exports.override = overrideModule;

}).call(this);
